### ISSUE TITLE
GPCalibration (maybe gpflow?) causes matplotlib figure rendering to crash

### ISSUE THREAD

**Issue by frederikfaye** [JonathanWenger/pycalib#3]
The following code produces the error below, making it impossible to use the GPCalibration class in a script that renders a figure:

```python
import matplotlib.pyplot as plt
from pycalib.calibration_methods import GPCalibration

fig,ax = plt.subplots()
ax.plot([0,1], [0,1])

# If either of the two lines are present, we get the error
plt.tight_layout()
plt.savefig('test.png')
```

```bash
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 291, in __init__
    cwd=self.tmpdir)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xelatex': 'xelatex'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mlp_test.py", line 8, in <module>
    plt.tight_layout()
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1337, in tight_layout
    gcf().tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/figure.py", line 2489, in tight_layout
    renderer = get_renderer(self)
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/tight_layout.py", line 222, in get_renderer
    renderer = canvas.get_renderer()
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 966, in get_renderer
    return RendererPgf(self.figure, None, dummy=True)
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 420, in __init__
    self._latexManager = LatexManager._get_cached_or_new()  # deprecated
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 241, in _get_cached_or_new
    return cls._get_cached_or_new_impl(cls._build_latex_header())
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 246, in _get_cached_or_new_impl
    return cls()
  File "/home/user/.local/lib/python3.6/site-packages/matplotlib/backends/backend_pgf.py", line 295, in __init__
    "pgf.texsystem to the desired command." % self.texcommand)
RuntimeError: Latex command not found. Install 'xelatex' or change pgf.texsystem to the desired command.
```

Thanks for your awesome work btw! :)

**Comment by JonathanWenger** [comment]
This is due to `texfig.py` which uses a `tex` backend to matplotlib to generate plots which LaTeX fonts. You can either ensure you have a matching tex installation or to adjust the matplotlib parameters to avoid this error. Here are the parameter settings in `texfig.py` which cause the error:

```python
mpl.rcParams.update({
    "text.usetex": True,
    "pgf.texsystem": "xelatex",
    "pgf.rcfonts": False,
    "font.family": "serif",
    "font.serif": [],
    "font.sans-serif": [],
    "font.monospace": [],
    "figure.figsize": [default_width, default_width * default_ratio],
    "pgf.preamble": [
        # put LaTeX preamble declarations here
        r"\usepackage[utf8x]{inputenc}",
        r"\usepackage[T1]{fontenc}",
        r"\usepackage{amsmath}",
        r"\usepackage{bm}"
        # macros defined here will be available in plots, e.g.:
        r"\newcommand{\vect}[1]{#1}",
        # You can use dummy implementations, since your  LaTeX document
        # will render these properly, anyway.
    ],
})
```

In particular ``` "pgf.texsystem": "xelatex",``` is the culprit and causes this error if `xelatex` is not available.
